### ISSUE TITLE
Can we hide the children node when children is empty?

### ISSUE THREAD

**Issue by AntonSmir** [mwc/treeify#1]
`{
        id: 'a',
        parentId: '',
        children: [
            {
                id: 'a1',
                parentId: 'a',
                children: [
                    {
                        id: 'a1-1',
                        parentId: 'a1'
                    }
                ]
            },
            {
                id: 'a2',
                parentId: 'a',
                children: [
                    {
                        id: 'aq',
                        parentId: 'a2'
                    }
                ]
            }
        ]
    }`

**Comment by maorui2014** [comment]
The feature is rejected.
I have to take more time to think deeply about it.
here are my suggestions for you:
1. you can do it by yourself after you get the tree.
2. or check the length of children when enumerate  the tree.

**Comment by mwc** [comment]
The feature is rejected.
I have to take more time to think deeply about it.
here are my suggestions for you:

you can do it by yourself after you get the tree.
or check the length of children when enumerate the tree.
