### ISSUE TITLE
Node Import Module Errors

### ISSUE THREAD

**Issue by christo911** [mwc/treeify#2]
Hi, encountering some errors when importing using the usual way..

`import {treeify} from 'treeify'`

Node and typescript giving errors.

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ..../node_modules/treeify-js/dist/treeify.js
require() of ES modules is not supported. `

And typescript errors.

`Could not find a declaration file for module 'treeify-js'. '..../backend/node_modules/treeify-js/dist/treeify.js' implicitly has an 'any' type.
Try npm install @types/treeify-js if it exists or add a new declaration (.d.ts) file containing declare module 'treeify-js';`

node error is resolved by deleting from your package.json "type": "module".
The type errors are resolved by adding to your dist folder a file named:  

treeify.d.ts 
`export declare function treeify(data: any[], configure: Object): any;
export declare function untreeify(tree: Object, childrenName: string): any;`

**Comment by mwc** [comment]
@stoffason

import like this pls:
``` js
import { treeify } from 'treeify-js'
```

the package name is `treeify-js` but not `treeify`, cuz `treeify` has been used.
